import { Product, Hospital, Review, Reservation, Post, Comment, Notification, Coupon, PointHistory } from '@/types';

export const categories = [
  { id: 'dental', name: '치과', icon: '/icons/dental.svg', popular: true },
  { id: 'hair', name: '모발', icon: '/icons/hair.svg', popular: false },
  { id: 'eye', name: '안과', icon: '/icons/eye.svg', popular: false },
  { id: 'ent', name: '이비인후과', icon: '/icons/ent.svg', popular: false },
  { id: 'pediatric', name: '소아과', icon: '/icons/pediatric.svg', popular: false },
  { id: 'urology', name: '비뇨/산부', icon: '/icons/urology.svg', popular: false },
  { id: 'orthopedic', name: '정형외과', icon: '/icons/orthopedic.svg', popular: false },
  { id: 'plastic', name: '성형외과', icon: '/icons/plastic.svg', popular: false },
];

export const dentalSubCategories = [
  '전체', '치아교정', '라미네이트', '미백제도포', '임플란트', '충치치료', '스케일링'
];

export const regions = [
  '서울시 강남구', '서울시 서초구', '서울시 동작구', '서울시 금천구',
  '서울시 양천구', '서울시 마포구', '서울시 종로구', '서울시 중구',
  '서울시 강동구', '서울시 송파구', '서울시 관악구', '서울시 영등포구',
];

export const popularSearches = [
  '위고비', '삭센다', '탈모', '비만', '피로', '우울증', '불안', '불면증', '고혈압', '당뇨'
];

export const communityTags = [
  '전문의토론', '개원의모임', '임상케이스', '임상의학',
  '의학정보공유', '진료노하우', '치료전략', '진단토론',
  '의료정책', '의료법', '병원경영', '환자상담', '처방가이드',
  '의학연구', '학회정보', '세미나공유', '의료트렌드',
  '근거중심의학', 'EBM', '전공의수련', '봉직의', '개원준비',
  '의료마케팅', '의료윤리', '의료이슈', '보험청구', '수가관리',
  '메디컬네트워크'
];

export const products: Product[] = [
  {
    id: '1',
    title: '원데이 치아미백 3회',
    hospitalName: '레브치과의원',
    hospitalId: 'h1',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    price: 55000,
    originalPrice: 110000,
    discount: 50,
    rating: 5.0,
    reviewCount: 15,
    likeCount: 8,
    imageUrl: '/images/product1.jpg',
    tags: ['#치아미백', '#신사역치아미백', '#강남치아미백'],
    category: 'dental',
    subCategory: '미백제도포',
  },
  {
    id: '2',
    title: '무삭제로네이트 라미네이트',
    hospitalName: '아이디치과',
    hospitalId: 'h2',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    price: 759000,
    originalPrice: 1200000,
    rating: 5.0,
    reviewCount: 15,
    likeCount: 8,
    imageUrl: '/images/product2.jpg',
    tags: ['#제로네이트', '#라미네이트', '#미백', '#치아교정'],
    category: 'dental',
    subCategory: '라미네이트',
  },
  {
    id: '3',
    title: '무삭제 폴리네이트',
    hospitalName: '레브치과의원',
    hospitalId: 'h1',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    price: 385000,
    originalPrice: 500000,
    rating: 5.0,
    reviewCount: 15,
    likeCount: 8,
    imageUrl: '/images/product3.jpg',
    tags: ['#치아미백', '#신사역치아미백', '#강남치아미백'],
    category: 'dental',
    subCategory: '라미네이트',
  },
  {
    id: '4',
    title: '디데이 치아미백 11',
    hospitalName: '참포도나무치과의원',
    hospitalId: 'h3',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    price: 759000,
    originalPrice: 1500000,
    rating: 5.0,
    reviewCount: 15,
    likeCount: 8,
    imageUrl: '/images/product4.jpg',
    tags: ['#제로네이트', '#라미네이트', '#미백', '#치아교정'],
    category: 'dental',
    subCategory: '미백제도포',
  },
  {
    id: '5',
    title: '공식 키닥터 온리프 올타이트 리프팅',
    hospitalName: '온리프성형외과의원',
    hospitalId: 'h4',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    price: 195900,
    originalPrice: 350000,
    discount: 44,
    rating: 4.0,
    reviewCount: 86,
    likeCount: 8,
    imageUrl: '/images/product5.jpg',
    tags: ['#리프팅', '#올타이트', '#피부시술'],
    category: 'plastic',
    subCategory: '리프팅',
    options: [
      { id: 'o1', name: '온리프 올타이트 리프팅 100샷', price: 195900 },
      { id: 'o2', name: '온리프 올타이트 리프팅 100샷', price: 699600 },
    ]
  },
  {
    id: '6',
    title: '눈밑지방재배치+애교살',
    hospitalName: '온리프성형외과의원',
    hospitalId: 'h4',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    price: 880000,
    rating: 5.0,
    reviewCount: 15,
    likeCount: 8,
    imageUrl: '/images/product6.jpg',
    tags: ['#눈밑지방재배치', '#애교살'],
    category: 'plastic',
    subCategory: '눈',
  },
];

export const hospitals: Hospital[] = [
  {
    id: 'h1',
    name: '레브치과의원',
    category: '치과',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    phone: '02-555-1234',
    tags: ['치아미백', '라미네이트', '폴리네이트'],
    coverImages: ['/images/hospital_h1.jpg'],
    introduction: '레브치과의원은 최신 장비와 숙련된 의료진이 함께하는 프리미엄 치과입니다.',
    operatingHours: [
      { day: '월', startTime: '10:00', endTime: '19:00' },
      { day: '화', startTime: '10:00', endTime: '21:00' },
      { day: '수', startTime: '10:00', endTime: '19:00' },
      { day: '목', startTime: '10:00', endTime: '19:00' },
      { day: '금', startTime: '10:00', endTime: '21:00' },
      { day: '토', startTime: '10:00', endTime: '16:00' },
    ],
    holidayNotice: '*공휴일 휴진',
    address: '서울 서초구 강남대로 399',
    doctors: [
      { id: 'd20', name: '박지훈', title: '대표원장', specialty: '보존과 전문의', hospitalName: '레브치과의원', hospitalId: 'h1', isOwner: true, bio: '서울대학교 치의학 박사. 15년간 보존 치료 전문. 미세현미경을 활용한 정밀 치료를 추구합니다.', careers: ['서울대학교 치의학과 졸업', '서울대학교 치의학 석사/박사', '대한보존학회 정회원', '레브치과의원 대표원장 (2015~현재)'], certifications: ['보존과 전문의', '대한치과의사협회'] },
      { id: 'd21', name: '최수진', title: '원장', specialty: '심미치과 전문의', hospitalName: '레브치과의원', hospitalId: 'h1', bio: '연세대학교 치의학과 졸업. 심미보철과 라미네이트 시술 경험 3,000건 이상.', careers: ['연세대학교 치의학과 졸업', '연세대학교 치과병원 수련', '레브치과의원 원장 (2018~현재)'], certifications: ['심미치과 전문의'] },
    ],
    rating: 5.0,
    reviewCount: 120,
  },
  {
    id: 'h2',
    name: '아이디치과',
    category: '치과',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    phone: '02-555-5678',
    tags: ['제로네이트', '라미네이트', '치아교정'],
    coverImages: ['/images/hospital_h2.jpg'],
    introduction: '아이디치과는 인비절라인 최고 등급을 달성한 치과입니다.',
    operatingHours: [
      { day: '월', startTime: '10:00', endTime: '19:00' },
      { day: '화', startTime: '10:00', endTime: '21:00' },
      { day: '수', startTime: '10:00', endTime: '19:00' },
      { day: '목', startTime: '10:00', endTime: '19:00' },
      { day: '금', startTime: '10:00', endTime: '21:00' },
      { day: '토', startTime: '10:00', endTime: '16:00' },
    ],
    holidayNotice: '*공휴일 휴진',
    address: '서울 서초구 강남대로 399',
    doctors: [
      { id: 'd22', name: '김태영', title: '대표원장', specialty: '치과교정과 전문의', hospitalName: '아이디치과', hospitalId: 'h2', isOwner: true, bio: '교정과 전문의. 인비절라인 다이아몬드 등급 달성. 비발치 교정과 투명교정 전문.', careers: ['고려대학교 치의학과 졸업', '고려대학교 치과병원 교정과 수련', '인비절라인 다이아몬드 프로바이더', '아이디치과 대표원장 (2016~현재)'], certifications: ['치과교정과 전문의'] },
      { id: 'd23', name: '이서연', title: '원장', specialty: '심미보철과 전문의', hospitalName: '아이디치과', hospitalId: 'h2', bio: '심미보철 전문. 자연스러운 라미네이트와 제로네이트 시술 5,000건 이상.', careers: ['경희대학교 치의학과 졸업', '경희대 치과병원 보철과 수련', '아이디치과 원장 (2019~현재)'], certifications: ['심미보철과 전문의'] },
    ],
    rating: 4.8,
    reviewCount: 250,
  },
  {
    id: 'h3',
    name: '참포도나무치과의원',
    category: '치과',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    phone: '1588-0831',
    tags: ['치아교정', '임플란트', '라미네이트'],
    coverImages: ['/images/hospital1.jpg'],
    introduction: '',
    operatingHours: [
      { day: '월', startTime: '10:00', endTime: '19:00' },
      { day: '화', startTime: '10:00', endTime: '21:00' },
      { day: '수', startTime: '10:00', endTime: '19:00' },
      { day: '목', startTime: '10:00', endTime: '19:00' },
      { day: '금', startTime: '10:00', endTime: '21:00' },
      { day: '토', startTime: '10:00', endTime: '16:00' },
    ],
    holidayNotice: '*공휴일 휴진',
    address: '서울 서초구 양재동 20-7',
    addressDetail: '양재역 8번 출구 방향 도보 5분 이내 위치 양재역 7번 출구에서 셔틀버스 통해 간편하게 내원 가능합니다.(운영시간 병원 문의)\n참포도나무의원',
    doctors: [
      { id: 'd1', name: '이양구', title: '대표원장', specialty: '치과교정과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', isOwner: true, bio: '교정과 전문의 15년 경력. 비발치 교정, 투명교정, 소아교정 전문. 환자 개개인에 맞춘 맞춤형 교정 치료를 제공합니다.', careers: ['서울대학교 치의학과 졸업', '서울대학교 치과병원 교정과 수련', '대한치과교정학회 인정의', '참포도나무치과의원 대표원장 (2012~현재)'], certifications: ['치과교정과 전문의', '인비절라인 공인 술자'] },
      { id: 'd2', name: '김민수', title: '원장', specialty: '통합치의학과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', bio: '통합치의학 전문의. 임플란트, 보철, 심미치료를 아우르는 통합 진료를 제공합니다.', careers: ['연세대학교 치의학과 졸업', '연세대 치과병원 수련', '참포도나무치과의원 원장 (2015~현재)'], certifications: ['통합치의학과 전문의'] },
      { id: 'd3', name: '송지혜', title: '원장', specialty: '통합치의학과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', bio: '보존 치료와 심미 수복 전문. 자연치아 보존을 최우선으로 합니다.', careers: ['경희대학교 치의학과 졸업', '참포도나무치과의원 원장 (2017~현재)'], certifications: ['통합치의학과 전문의'] },
      { id: 'd4', name: '강준구', title: '원장', specialty: '치과교정과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', bio: '성인 교정 전문. 설측교정, 투명교정 다수 경험.', careers: ['고려대학교 치의학과 졸업', '참포도나무치과의원 원장 (2018~현재)'], certifications: ['치과교정과 전문의'] },
      { id: 'd5', name: '황선화', title: '원장', specialty: '치주과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', bio: '잇몸 치료 전문. 치주 수술 및 임플란트 주위 관리 전문.', careers: ['부산대학교 치의학과 졸업', '참포도나무치과의원 원장 (2019~현재)'], certifications: ['치주과 전문의'] },
      { id: 'd6', name: '송원용', title: '원장', specialty: '치과교정과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', bio: '소아/청소년 교정 전문.', careers: ['전남대학교 치의학과 졸업', '참포도나무치과의원 원장 (2020~현재)'], certifications: ['치과교정과 전문의'] },
      { id: 'd7', name: '한희태', title: '원장', specialty: '치과보철과 전문의', hospitalName: '참포도나무치과의원', hospitalId: 'h3', bio: '보철과 전문의. 정밀 보철과 심미 보철 전문.', careers: ['단국대학교 치의학과 졸업', '참포도나무치과의원 원장 (2020~현재)'], certifications: ['치과보철과 전문의'] },
    ],
    rating: 5.0,
    reviewCount: 1391,
  },
  {
    id: 'h4',
    name: '온리프성형외과의원',
    category: '성형외과',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    phone: '02-1234-5678',
    tags: ['눈', '코', '리프팅'],
    coverImages: [],
    operatingHours: [
      { day: '월', startTime: '10:00', endTime: '19:00' },
      { day: '화', startTime: '10:00', endTime: '21:00' },
      { day: '수', startTime: '10:00', endTime: '19:00' },
      { day: '목', startTime: '10:00', endTime: '19:00' },
      { day: '금', startTime: '10:00', endTime: '21:00' },
      { day: '토', startTime: '10:00', endTime: '16:00' },
    ],
    address: '서울 서초구 양재동 20-7',
    doctors: [
      { id: 'd10', name: '이재은', title: '대표원장', specialty: '성형외과 전문의', hospitalName: '온리프성형외과의원', isOwner: true },
      { id: 'd11', name: '이상엽', title: '원장', specialty: '', hospitalName: '온리프성형외과의원' },
      { id: 'd12', name: '조윤지', title: '원장', specialty: '', hospitalName: '온리프성형외과의원' },
      { id: 'd13', name: '강준구', title: '원장', specialty: '', hospitalName: '온리프성형외과의원' },
      { id: 'd14', name: '황선화', title: '원장', specialty: '', hospitalName: '온리프성형외과의원' },
      { id: 'd15', name: '송원용', title: '원장', specialty: '', hospitalName: '온리프성형외과의원' },
      { id: 'd16', name: '한희태', title: '원장', specialty: '', hospitalName: '온리프성형외과의원' },
      { id: 'd17', name: '최윤진', title: '원장', specialty: '피부과 전문의', hospitalName: '온리프성형외과의원' },
    ],
    rating: 5.0,
    reviewCount: 86,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    authorName: '넥스트알유',
    authorId: 'u1',
    date: '2025년 12월 3일',
    rating: 4.0,
    content: '이가 선척적으로 노래서 ㅠㅠ 미백해봐도 효과가 거의 없더라고용.. 거기에 토끼이빨까지 있어서 웃을 때 뻔 깨는 느낌이라 이번에 제로네이트 했어요!!! 제가 원하는 디자인 사진 가져갔고 최대한 없고 , 자연스럽게 희망했는데 원장님이 꼼꼼하게 잘 봐주셔서 제가 원했던대로 디자인 잘 나온거같습니다^_^ 과하게 인위적인 느낌도 없구 요즘 사진찍을때 남녀댕! 새해기념으로 나에게 주는선물이었는데 제가 살면서 해본 시술중에 젤 만족쿠해요',
    treatmentName: '무삭제로네이트 라미네이트',
    totalCost: 759000,
    treatmentDate: '2025년 02월 19일',
    productId: '2',
    hospitalId: 'h2',
  },
  {
    id: 'r2',
    authorName: '옹잉아옹유양',
    authorId: 'u2',
    date: '2025년 12월 3일',
    rating: 4.0,
    content: '강남역 온리프 성형외과에서 인모드, 슈링크 동시 진행 솔직후기 3주차입니다 😊😊 당일 직후 바로 보이는 즉각적인 효과에도 꽤 만족스러웠는데 3주가 흐른 지금 만나는 사람들마다 다 살 그만 빼지라고 하네요.. 사실 비법은 다이어트가 아니라 리프팅인데😋😋 이제 인모드 슈링크는 너무 대중적이라 저도 리프팅을 고르는 병원 기준이 핸들링이에요 꼭 온리프 성형외과여야만 하는 이유를 알려드리자면 ✨김하린 원장님💛이 계시는 것입니다 응 신기하게 즉각적으로 바로 보이는 즉각적 효과, 피부 탄력과 본인의 컴플렉스를 말씀 드리면 디자이너 였다고 해서 엄청 꼼꼼하게 하시는 것 같았어요.',
    treatmentName: '무삭제로네이트 라미네이트',
    totalCost: 759000,
    treatmentDate: '2025년 10월 28일',
    productId: '2',
    hospitalId: 'h4',
  },
  {
    id: 'r3',
    authorName: '쌩인디오',
    authorId: 'u3',
    date: '2025년 12월 3일',
    rating: 4.0,
    content: '이쁘되면 리프팅 집착녀 ... 온리프에서 얼굴소멜 3종시술 리 열후기들고옴! \'올타이트 300s + ON리프팅주사2cc + 사각턱보톡스\' 올타이트는 생소한 리프팅 시술인데, 고통없이 예뻐질 수 있다고해서 하고왔어요!',
    treatmentName: '레이저리프팅, 턱 지방분해/윤곽주사, 콜라겐부스',
    totalCost: 100000,
    treatmentDate: '2025년 02월 19일',
    productId: '5',
    hospitalId: 'h4',
    doctorId: 'd10',
    doctorName: '이재은 대표원장',
  },
  {
    id: 'r4',
    authorName: '밍밍이',
    authorId: 'u4',
    date: '2026년 1월 15일',
    rating: 5.0,
    content: '이양구 원장님께 교정 상담 받았는데 정말 꼼꼼하게 설명해주셨어요. 비발치로 가능하다고 하셔서 너무 기쁘고, 치료 계획도 상세하게 세워주셨습니다. 교정 전문의라 그런지 신뢰가 갑니다!',
    treatmentName: '치아교정',
    totalCost: 450000,
    treatmentDate: '2025년 12월 10일',
    hospitalId: 'h3',
    doctorId: 'd1',
    doctorName: '이양구 대표원장',
  },
  {
    id: 'r5',
    authorName: '치아요정',
    authorId: 'u5',
    date: '2026년 2월 3일',
    rating: 4.5,
    content: '김민수 원장님 임플란트 시술 후기입니다. 통증이 거의 없었고 회복도 빨랐어요. 사후관리까지 신경 써주셔서 감사합니다. 다음에도 김민수 원장님께 치료 받고 싶습니다.',
    treatmentName: '임플란트',
    totalCost: 1200000,
    treatmentDate: '2026년 1월 5일',
    hospitalId: 'h3',
    doctorId: 'd2',
    doctorName: '김민수 원장',
  },
  {
    id: 'r6',
    authorName: '스마일퀸',
    authorId: 'u6',
    date: '2026년 3월 12일',
    rating: 5.0,
    content: '박지훈 대표원장님께 치아미백 받았어요! 원래 누런 편이었는데 3회 시술 후 확실히 밝아졌습니다. 시술 과정도 편안했고 원장님이 친절하게 설명해주셨어요.',
    treatmentName: '원데이 치아미백 3회',
    totalCost: 55000,
    treatmentDate: '2026년 2월 20일',
    hospitalId: 'h1',
    doctorId: 'd20',
    doctorName: '박지훈 대표원장',
  },
  {
    id: 'r7',
    authorName: '라미네이트짱',
    authorId: 'u7',
    date: '2026년 3월 25일',
    rating: 4.0,
    content: '이서연 원장님 라미네이트 정말 자연스럽게 해주셨어요. 제가 원하는 색상과 모양을 정확히 반영해주셨고, 결과물이 너무 만족스럽습니다.',
    treatmentName: '무삭제로네이트 라미네이트',
    totalCost: 759000,
    treatmentDate: '2026년 3월 1일',
    hospitalId: 'h2',
    doctorId: 'd23',
    doctorName: '이서연 원장',
  },
  {
    id: 'r8',
    authorName: '예쁜이빨',
    authorId: 'u8',
    date: '2026년 1월 8일',
    rating: 5.0,
    content: '치아미백 3회 다녀왔어요! 처음에는 반신반의했는데 진짜 확 달라졌어요. 커피를 많이 마셔서 누렇게 변색됐었는데 시술 후 거울 볼 때마다 기분이 좋아요. 시술 시간도 30분 정도밖에 안 걸려서 점심시간에 다녀올 수 있었어요. 레브치과 강추합니다!',
    treatmentName: '원데이 치아미백 3회',
    totalCost: 55000,
    treatmentDate: '2025년 12월 15일',
    productId: '1',
    hospitalId: 'h1',
    doctorId: 'd20',
    doctorName: '박지훈 대표원장',
  },
  {
    id: 'r9',
    authorName: '교정소녀',
    authorId: 'u9',
    date: '2026년 2월 14일',
    rating: 4.5,
    content: '강준구 원장님한테 투명교정 상담받았어요. 제 치아 상태를 3D 스캔해서 보여주시면서 교정 후 예상 모습까지 보여주셨어요. 비발치로 가능하다고 하셔서 정말 다행이에요. 교정 기간도 1년 정도면 된다고 하시네요. 상담만 받았는데도 벌써 기대돼요!',
    treatmentName: '투명교정 상담',
    totalCost: 0,
    treatmentDate: '2026년 2월 10일',
    hospitalId: 'h3',
    doctorId: 'd4',
    doctorName: '강준구 원장',
  },
  {
    id: 'r10',
    authorName: '건강한잇몸',
    authorId: 'u10',
    date: '2025년 11월 20일',
    rating: 4.0,
    content: '잇몸이 계속 부어서 황선화 원장님께 진료받았어요. 치주 치료를 꼼꼼하게 해주셨고, 양치질 방법도 자세히 알려주셨어요. 치료 후 잇몸 상태가 확실히 좋아졌습니다. 정기적으로 관리 받으러 다닐 예정이에요.',
    treatmentName: '치주치료',
    totalCost: 180000,
    treatmentDate: '2025년 11월 5일',
    hospitalId: 'h3',
    doctorId: 'd5',
    doctorName: '황선화 원장',
  },
  {
    id: 'r11',
    authorName: '보철왕',
    authorId: 'u11',
    date: '2026년 3월 2일',
    rating: 5.0,
    content: '한희태 원장님께 크라운 치료 받았습니다. 오래된 크라운을 교체해야 했는데, 디지털 스캔으로 정밀하게 제작해주셔서 기존 치아와 색감이 거의 동일해요. 씹는 느낌도 자연스럽고 정말 만족합니다. 보철 전문의라 역시 다르네요.',
    treatmentName: '크라운 보철',
    totalCost: 450000,
    treatmentDate: '2026년 2월 15일',
    hospitalId: 'h3',
    doctorId: 'd7',
    doctorName: '한희태 원장',
  },
  {
    id: 'r12',
    authorName: '자연미인',
    authorId: 'u12',
    date: '2026년 1월 28일',
    rating: 5.0,
    content: '최수진 원장님께 라미네이트 8개 했어요. 처음엔 걱정이 많았는데 원장님이 자연스러운 쉐이드로 추천해주셔서 결과가 정말 자연스러워요. 주변에서 성형한 거 아니냐고 물어볼 정도! 웃을 때 자신감이 생겼어요. 시술 후 관리법도 꼼꼼히 알려주셨습니다.',
    treatmentName: '라미네이트 8개',
    totalCost: 3200000,
    treatmentDate: '2026년 1월 10일',
    productId: '2',
    hospitalId: 'h1',
    doctorId: 'd21',
    doctorName: '최수진 원장',
  },
  {
    id: 'r13',
    authorName: '교정맘',
    authorId: 'u13',
    date: '2026년 2월 22일',
    rating: 4.5,
    content: '초등학생 아이 교정 때문에 방문했어요. 이양구 대표원장님이 아이 눈높이에 맞춰서 설명해주시고, 치료 과정을 애니메이션으로 보여주셔서 아이도 무서워하지 않았어요. 소아교정 경험이 풍부하신 것 같아서 안심이 됩니다.',
    treatmentName: '소아교정',
    totalCost: 350000,
    treatmentDate: '2026년 2월 1일',
    hospitalId: 'h3',
    doctorId: 'd1',
    doctorName: '이양구 대표원장',
  },
  {
    id: 'r14',
    authorName: '리프팅매니아',
    authorId: 'u14',
    date: '2026년 3월 18일',
    rating: 4.0,
    content: '올타이트 리프팅 100샷 받았어요. 시술 시간이 20분 정도로 짧았고, 통증도 거의 없었어요. 시술 직후부터 턱라인이 좀 더 선명해진 느낌이에요. 2주 지나니까 더 효과가 나타나는 것 같아요. 가격 대비 만족스럽습니다.',
    treatmentName: '온리프 올타이트 리프팅 100샷',
    totalCost: 195900,
    treatmentDate: '2026년 3월 5일',
    productId: '5',
    hospitalId: 'h4',
    doctorId: 'd10',
    doctorName: '이재은 대표원장',
  },
  {
    id: 'r15',
    authorName: '눈밑고민해결',
    authorId: 'u15',
    date: '2026년 2월 10일',
    rating: 5.0,
    content: '눈밑지방재배치 받았는데 결과가 정말 놀라워요! 항상 피곤해 보인다는 소리를 들었는데 시술 후에는 얼굴이 환해졌다는 말을 많이 들어요. 붓기는 1주일 정도 있었지만 그 후로는 자연스러워졌어요. 온리프성형외과 추천합니다!',
    treatmentName: '눈밑지방재배치+애교살',
    totalCost: 880000,
    treatmentDate: '2026년 1월 20일',
    productId: '6',
    hospitalId: 'h4',
    doctorId: 'd11',
    doctorName: '이상엽 원장',
  },
  {
    id: 'r16',
    authorName: '교정완료자',
    authorId: 'u16',
    date: '2025년 12월 28일',
    rating: 5.0,
    content: '김태영 대표원장님한테 인비절라인 교정 2년 만에 완료했어요! 중간에 힘들 때도 있었지만 원장님이 매번 격려해주시고 세심하게 관리해주셔서 끝까지 할 수 있었어요. 결과가 너무 만족스럽고, 사진 찍을 때 활짝 웃을 수 있게 됐어요!',
    treatmentName: '인비절라인 교정',
    totalCost: 5500000,
    treatmentDate: '2025년 12월 20일',
    hospitalId: 'h2',
    doctorId: 'd22',
    doctorName: '김태영 대표원장',
  },
  {
    id: 'r17',
    authorName: '미백도전기',
    authorId: 'u17',
    date: '2026년 3월 30일',
    rating: 4.0,
    content: '디데이 치아미백 받았어요. 솔직히 한 번에 연예인 치아가 되진 않지만, 3-4단계 정도 밝아진 건 확실해요. 커피 마시는 습관은 줄여야 유지된다고 하시더라고요. 가격 대비 괜찮은 것 같아요. 유지 관리만 잘하면 될 듯!',
    treatmentName: '디데이 치아미백 11',
    totalCost: 759000,
    treatmentDate: '2026년 3월 15일',
    productId: '4',
    hospitalId: 'h3',
    doctorId: 'd3',
    doctorName: '송지혜 원장',
  },
  {
    id: 'r18',
    authorName: '폴리네이트후기',
    authorId: 'u18',
    date: '2026년 2월 5일',
    rating: 4.5,
    content: '무삭제 폴리네이트 4개 했어요. 라미네이트보다 저렴하면서도 자연스러운 결과가 나왔어요. 원래 앞니 사이에 틈이 있었는데 깔끔하게 메워졌어요. 시술 시간도 1시간 정도로 빨랐고, 마취도 안 해서 편했어요.',
    treatmentName: '무삭제 폴리네이트',
    totalCost: 385000,
    treatmentDate: '2026년 1월 25일',
    productId: '3',
    hospitalId: 'h1',
    doctorId: 'd21',
    doctorName: '최수진 원장',
  },
  {
    id: 'r19',
    authorName: '임플란트생존기',
    authorId: 'u19',
    date: '2026년 3월 8일',
    rating: 5.0,
    content: '어금니 임플란트 2개 식립했어요. 솔직히 겁이 많아서 미루고 미뤘는데, 김민수 원장님이 전체 과정을 차근차근 설명해주시고 수술도 정말 빠르게 끝났어요. 수술 후 붓기도 생각보다 적었고, 지금은 자연 치아처럼 씹을 수 있어요. 진작 할 걸 그랬어요!',
    treatmentName: '임플란트 2개',
    totalCost: 2400000,
    treatmentDate: '2026년 2월 20일',
    hospitalId: 'h3',
    doctorId: 'd2',
    doctorName: '김민수 원장',
  },
  {
    id: 'r20',
    authorName: '코필러후기양',
    authorId: 'u20',
    date: '2026년 4월 1일',
    rating: 4.0,
    content: '조윤지 원장님께 코필러 받았어요. 코끝이 살짝 올라가면서 전체적으로 세련된 느낌이 났어요. 시술 시간 10분, 통증 거의 없음, 다운타임도 하루면 충분했어요. 자연스러운 변화를 원하시는 분들께 추천합니다!',
    treatmentName: '코필러',
    totalCost: 250000,
    treatmentDate: '2026년 3월 28일',
    hospitalId: 'h4',
    doctorId: 'd12',
    doctorName: '조윤지 원장',
  },
  {
    id: 'r21',
    authorName: '스케일링정기권',
    authorId: 'u21',
    date: '2026년 1월 3일',
    rating: 4.5,
    content: '6개월마다 정기 스케일링 받고 있어요. 송원용 원장님이 매번 꼼꼼하게 해주시고 치석이 잘 끼는 부위도 알려주셔서 집에서 관리하기 편해요. 스케일링 후 이가 시린 증상도 거의 없었어요. 가격도 합리적이고 예약도 잘 돼서 좋아요.',
    treatmentName: '스케일링',
    totalCost: 50000,
    treatmentDate: '2025년 12월 28일',
    hospitalId: 'h3',
    doctorId: 'd6',
    doctorName: '송원용 원장',
  },
  {
    id: 'r22',
    authorName: '보톡스첫경험',
    authorId: 'u22',
    date: '2026년 3월 22일',
    rating: 5.0,
    content: '사각턱 보톡스 처음 맞아봤는데 진짜 효과 있네요! 황선화 원장님이 제 얼굴형에 맞게 양을 조절해주셨어요. 시술 2주 후부터 확실히 턱이 갸름해졌어요. 표정도 자연스럽고 일상생활에 전혀 지장 없었어요. 3개월 후에 한 번 더 맞으러 갈 예정!',
    treatmentName: '사각턱 보톡스',
    totalCost: 120000,
    treatmentDate: '2026년 3월 10일',
    hospitalId: 'h3',
    doctorId: 'd5',
    doctorName: '황선화 원장',
  },
];

export const reservations: Reservation[] = [
  {
    id: 'res1',
    status: 'cancelled',
    date: '2026년4월30일',
    productTitle: '공식 키닥터 온리프 올타이트 리프팅',
    productImage: '/images/product5.jpg',
    hospitalName: '온리프성형외과의원',
    hospitalId: 'h4',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    visitDate: '2026년3월26일 오전 12:00',
    reservationDate: '2026년3월26일 오전 12:00',
    cancelDate: '2026년3월26일 오전 12:00',
    amount: 130000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
    cancelReason: '안녕하세요 고객님! 온리프성형외과의원입니다. 다름이 아니라 해당일에 저희가 모두 휴진상태입니다. 예약화면을 막아놨어야 했는데 그러지 못한점 죄송합니다. 본점을 통해서 고객님 휴대폰번호 뒷자리 공유 시 피부 시술권을 드리도록 하겠습니다 감사합니다.',
  },
  {
    id: 'res2',
    status: 'pending',
    date: '2026년4월30일',
    productTitle: '공식 키닥터 온리프 올타이트 리프팅',
    productImage: '/images/product5.jpg',
    hospitalName: '온리프성형외과의원',
    hospitalId: 'h4',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    visitDate: '2026년3월26일 오전 12:00',
    reservationDate: '2026년3월26일 오전 12:00',
    amount: 130000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
    paymentType: '앱결제',
    paymentMethod: 'KB국민카드',
  },
  {
    id: 'res3',
    status: 'confirmed',
    date: '2026년4월30일',
    productTitle: '공식 키닥터 온리프 올타이트 리프팅',
    productImage: '/images/product5.jpg',
    hospitalName: '온리프성형외과의원',
    hospitalId: 'h4',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    visitDate: '2026년3월26일 오전 12:00',
    reservationDate: '2026년3월26일 오전 12:00',
    amount: 130000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
  },
  {
    id: 'res4',
    status: 'completed',
    date: '2026년4월30일',
    productTitle: '공식 키닥터 온리프 올타이트 리프팅',
    productImage: '/images/product5.jpg',
    hospitalName: '온리프성형외과의원',
    hospitalId: 'h4',
    location: '서울 강남역 서울특별시 서초구 강남대로 399',
    visitDate: '2026년3월26일 오전 12:00',
    reservationDate: '2026년3월26일 오전 12:00',
    amount: 130000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
  },
  {
    id: 'res5',
    status: 'confirmed',
    date: '2026년5월12일',
    productTitle: '강남 프리미엄 루체 미백 4회 패키지',
    productImage: '/images/product1.jpg',
    hospitalName: '화이트밀 치과의원',
    hospitalId: 'h1',
    location: '서울 강남구 테헤란로 122',
    visitDate: '2026년5월20일 오후 02:30',
    reservationDate: '2026년5월20일 오후 02:30',
    amount: 280000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
  },
  {
    id: 'res6',
    status: 'pending',
    date: '2026년5월10일',
    productTitle: '오스템 SA 임플란트 단일 식립',
    productImage: '/images/product2.jpg',
    hospitalName: '바른이치과',
    hospitalId: 'h2',
    location: '서울 서초구 반포대로 200',
    visitDate: '2026년5월25일 오전 10:00',
    reservationDate: '2026년5월25일 오전 10:00',
    amount: 950000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
    paymentType: '앱결제',
    paymentMethod: 'KB국민카드',
  },
  {
    id: 'res7',
    status: 'completed',
    date: '2026년3월18일',
    productTitle: '인비절라인 교정 상/하악 진단 패키지',
    productImage: '/images/product3.jpg',
    hospitalName: '스마일라인 교정치과',
    hospitalId: 'h3',
    location: '서울 송파구 올림픽로 300',
    visitDate: '2026년3월28일 오후 03:00',
    reservationDate: '2026년3월28일 오후 03:00',
    amount: 450000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
  },
  {
    id: 'res8',
    status: 'confirmed',
    date: '2026년5월18일',
    productTitle: '라미네이트 전치부 6개 디자인 상담',
    productImage: '/images/product4.jpg',
    hospitalName: '더라임치과',
    hospitalId: 'h5',
    location: '서울 마포구 양화로 45',
    visitDate: '2026년5월28일 오후 05:00',
    reservationDate: '2026년5월28일 오후 05:00',
    amount: 180000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
  },
  {
    id: 'res9',
    status: 'pending',
    date: '2026년5월09일',
    productTitle: '사랑니 발치 + 수면 진정 케어',
    productImage: '/images/product6.jpg',
    hospitalName: '참포도나무치과의원',
    hospitalId: 'h6',
    location: '서울 서초구 양재동 20-7',
    visitDate: '2026년5월22일 오전 11:00',
    reservationDate: '2026년5월22일 오전 11:00',
    amount: 220000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
    paymentType: '앱결제',
    paymentMethod: '토스페이',
  },
  {
    id: 'res10',
    status: 'cancelled',
    date: '2026년4월22일',
    productTitle: '치아 스케일링 + 전문가 불소 도포',
    productImage: '/images/product7.jpg',
    hospitalName: '밝은이치과',
    hospitalId: 'h7',
    location: '서울 강동구 천호대로 1205',
    visitDate: '2026년4월28일 오전 09:30',
    reservationDate: '2026년4월28일 오전 09:30',
    cancelDate: '2026년4월24일 오후 08:12',
    amount: 55000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
    cancelReason: '개인 사정으로 방문이 어려워져 고객이 직접 취소하였습니다.',
  },
  {
    id: 'res11',
    status: 'completed',
    date: '2026년2월15일',
    productTitle: '어린이 충치 검진 + 실란트 2개',
    productImage: '/images/product8.jpg',
    hospitalName: '꼬마치과',
    hospitalId: 'h8',
    location: '서울 성동구 왕십리로 222',
    visitDate: '2026년2월25일 오후 04:00',
    reservationDate: '2026년2월25일 오후 04:00',
    amount: 85000,
    customerName: '홍길동',
    customerPhone: '010-1245-2189',
  },
];

export const posts: Post[] = [
  {
    id: 'p1',
    boardType: 'question',
    title: '개원 1년 차, 마케팅 ROI 실제 체감 어떠신가요?',
    content: '네이버 플레이스·지역 카페·SNS 광고를 병행 중입니다. 초기 3개월은 유입 대비 전환율이 낮았는데, 리뷰 관리와 예약 동선 개선...',
    authorName: '정준 대표원장',
    authorTitle: '대표원장',
    authorHospital: '',
    authorId: 'doc1',
    date: '2026.04.14',
    viewCount: 1535,
    likeCount: 0,
    commentCount: 10,
    tags: ['치과', '질문', '마케팅'],
    hasAnswer: true,
    answerCount: 10,
  },
  {
    id: 'p2',
    boardType: 'question',
    title: '임플란트 당일식립 케이스 선택 기준 공유',
    content: '골질 D2~D3 기준에서 35Ncm 이상 토크 확보 시 진행 중입니다. 전신질환자 관리 프로토콜은 어떻게 가져가시는지 궁금합니다.',
    authorName: '',
    authorId: 'doc2',
    date: '2026.04.14',
    viewCount: 0,
    likeCount: 0,
    commentCount: 2,
    imageUrl: '/images/post2.jpg',
    tags: ['치과', '질문', '마케팅'],
    hasAnswer: true,
    answerCount: 2,
  },
  {
    id: 'p3',
    boardType: 'question',
    title: '소아 고열 환자 응급실 전원 기준 재정리',
    content: '39도 이상 48시간 지속 + 탈수 소견 시 전원하고 있습니다. RSV 시즌이라 보호자 설명이 더 중요하네요. 현장 프로토콜 공유 부...',
    authorName: '',
    authorId: 'doc3',
    date: '2026.04.14',
    viewCount: 0,
    likeCount: 0,
    commentCount: 0,
    tags: ['치과', '질문', '마케팅'],
    hasAnswer: false,
  },
  {
    id: 'p4',
    boardType: 'question',
    title: '갑상선 결절 FNA 후 추적주기 어떻게 보시나요',
    content: 'Bethesda II는 6~12개월 추적 중입니다. 초음파 소견 변화가 경미할 때의 판단 기준이 고민입니다.',
    authorName: '',
    authorId: 'doc4',
    date: '2026.04.14',
    viewCount: 0,
    likeCount: 0,
    commentCount: 10,
    tags: ['치과', '질문', '마케팅'],
    hasAnswer: true,
    answerCount: 10,
  },
  {
    id: 'p5',
    boardType: 'dental',
    title: '미용시술 후 색소침착 최소화 팁',
    content: '레이저 강도 보수적으로 접근 후 재시술 전략이 안전하다고 느낍니다. 사후관리 안내문구 어떻게 작성하시나요?',
    authorName: '전영민 원장',
    authorTitle: '원장',
    authorHospital: '세라믹치과의원',
    authorId: 'doc5',
    date: '2026.04.14',
    viewCount: 16,
    likeCount: 0,
    commentCount: 6,
    imageUrl: '/images/post5.jpg',
    tags: ['치과', '질문', '마케팅'],
    hasAnswer: true,
    answerCount: 2,
  },
  {
    id: 'p6',
    boardType: 'dental',
    title: '비발치 교정, 어디까지 허용하시나요?',
    content: '최근 내원 환자들 중 "발치는 절대 원하지 않는다"는 요구가 확실히 늘었습니다. 특히 성인 교정에서 심미적 요구가 강해지면서, 가능하면 비발치로 접근하려는 경향이 강해진 것 같습니다.\n다만, 임상적으로는 crowding 6~7mm 이상이거나 상·하악 전돌이 동반된 케이스에서 무리한 비발치 진행 시\n특히 최근에는 IPR + 미니스크류(TAD) 병행으로 비발치 가능 범위가 넓어졌지만, 무리한 expansion은 장기 relapse 가능성이 높다고 느끼고 있습니다.',
    authorName: '이양구 대표원장',
    authorTitle: '대표원장',
    authorHospital: '포도나무치과의원',
    authorId: 'doc6',
    date: '2026.04.14',
    viewCount: 16,
    likeCount: 0,
    commentCount: 0,
    imageUrl: '/images/post6.jpg',
    tags: ['치료전략', '진단토론', '의료정책', '의료법', '근거중심의학'],
  },
  {
    id: 'p7',
    boardType: 'free',
    title: '스케일링 주기 환자에게 어떻게 설명하시나요?',
    content: '환자들이 스케일링을 1년에 한 번만 하면 되는 줄 아는 경우가 많습니다.',
    authorName: '',
    authorId: 'anon1',
    isAnonymous: true,
    anonymousId: '0217847',
    date: '2026.04.14',
    viewCount: 0,
    likeCount: 0,
    commentCount: 0,
    tags: [],
  },
  {
    id: 'p8',
    boardType: 'free',
    title: '교정 상담만 받고 안 오는 환자 많지 않나요?',
    content: '요즘 교정 상담만 하고 돌아가는 환자들이 꽤 많습니다. 시간을 많이 쓰게 되는데 실제 치료로 이어지는 비율이 생각보...',
    authorName: '',
    authorId: 'anon2',
    isAnonymous: true,
    anonymousId: '0895413',
    date: '2026.04.14',
    viewCount: 0,
    likeCount: 0,
    commentCount: 0,
    tags: [],
  },
];

export const comments: Comment[] = [
  {
    id: 'c1',
    postId: 'p5',
    authorName: '정준 대표원장',
    authorTitle: '대표원장',
    authorHospital: '더 뉴 치과의원',
    authorId: 'doc1',
    content: '보수적 접근에 동의합니다. 특히 멜라닌 활성 높은 환자군은 1회 강하게보다 3~5회 나누는 게 안전하더군요.\n저는 사후관리 문구를 "예상 반응 / 주의사항 / 이상 반응 시 대응" 3단 구조로 작성합니다.\n예시:\n1. 예상 반응: 붉어짐, 약간의 부기, 미세 각질\n2. 주의사항: 시술 부위 마찰 금지, 필링 제품 1주 중단\n3. 이상 반응: 심한 통증·수포 발생 시 즉시 병원 연락\n이렇게 구분하면 환자 불안이 확실히 줄어듭니다.\n특히 "자연 회복 기간은 5~7일"처럼 기간을 명확히 써주는 게 중요했습니다.',
    date: '2026.04.14',
    likeCount: 0,
  },
  {
    id: 'c2',
    postId: 'p5',
    authorName: '이양구 대표원장',
    authorTitle: '대표원장',
    authorHospital: '포도나무치과의원',
    authorId: 'doc6',
    content: '강도 낮추고 재시술 전략은 장기적으로 브랜드 신뢰에 더 도움이 된다고 생각합니다. 단기 만족도보다는 합병증 최소화가 핵심이니까요.\n저는 사후관리 안내문에 행동 금지 리스트를 강조합니다.\n• 시술 부위 손대지 않기\n• 각질 억지로 제거하지 않기\n• 고온 환경 노출 피하기\n• 미백·각질제거 제품 7일 금지\n그리고 마지막에\n"색소 침착은 일시적일 수 있으며, 필요 시 추가 케어를 통해 개선 가능합니다."\n라는 문장을 넣어 재방문 동선을 자연스럽게 만들어두고 있습니다.\n사후관리 문구는 결국 \'의학적 설명 + 심리적 안심\' 두 요소가 균형을 이루는 것이 핵심인 것 같습니다.',
    date: '2026.04.14',
    likeCount: 0,
  },
];

export const notifications: Notification[] = [
  { id: 'n1', type: 'event', title: '봄맞이 미소 리프레시 이벤트', content: '따뜻한 봄이 찾아왔어요. 새로운 계절, 환한 미소로 시작해보세요! 지금 인기 치과에서 스케일링, 치아미백, 교정 상담 봄맞이 특별 이벤트 진행 중! 지금 확인하고 혜택 받아보세요.', date: '2026.02.24', isRead: false },
  { id: 'n2', type: 'important', title: '예약 일정 안내', content: '예약하신 원데이 치아미백 3회 시술이 2026년 3월 26일 오전 12:00에 예정되어 있습니다. 병원 방문 시 신분증을 지참해주세요. 예약 변경은 하루 전까지 가능합니다.', date: '2026.07.01', isRead: false },
  { id: 'n3', type: 'recommendation', title: '회원님께 추천드리는 치과', content: '회원님의 관심 시술과 지역을 기반으로 맞춤 추천해드립니다. 강남역 주변 인기 치과 TOP 5를 확인해보세요. 첫 방문 시 특별 할인 혜택도 준비되어 있습니다.', date: '2026.07.01', isRead: true },
  { id: 'n4', type: 'info', title: '서비스 이용 안내', content: '키닥터 서비스를 더 편리하게 이용하실 수 있도록 안내드립니다. 예약 변경, 취소, 환불 정책이 일부 업데이트되었습니다. 자세한 내용은 마이페이지 > 약관에서 확인하실 수 있습니다.', date: '2026.07.01', isRead: true },
  { id: 'n5', type: 'update', title: '서비스 업데이트 안내', content: '키닥터 앱이 새롭게 업데이트되었습니다! 검색 필터 기능이 강화되어 지역, 가격대, 예약방법별로 더 쉽게 병원을 찾을 수 있습니다. 커뮤니티 기능도 개선되었습니다.', date: '2026.08.15', isRead: true },
  { id: 'n6', type: 'event', title: '여름 맞이 특가 이벤트', content: '무더운 여름, 시원한 미소로 이겨내세요! 인기 시술 최대 30% 할인 이벤트가 진행 중입니다. 라미네이트, 치아미백, 교정 상담까지 다양한 혜택을 만나보세요.', date: '2026.06.15', isRead: false },
  { id: 'n7', type: 'important', title: '결제 완료 안내', content: '무삭제로네이트 라미네이트 시술 결제가 완료되었습니다. 결제금액: 759,000원 / 결제수단: KB국민카드. 영수증은 마이페이지 > 결제내역에서 확인하실 수 있습니다.', date: '2026.05.20', isRead: true },
];

export const coupons: Coupon[] = [
  { id: 'cp1', name: '봄맞이 환한 미소 만들기 할인 쿠폰', description: '', discountAmount: 8000, expiryDate: '2026년12월10일', daysLeft: 10, status: 'available' },
  { id: 'cp2', name: '웰컴 디바이데이 쿠폰', description: '', discountAmount: 5000, expiryDate: '2026년12월10일', daysLeft: 24, status: 'available' },
  { id: 'cp3', name: '첫 방문 스마일 혜택 쿠폰', description: '', discountAmount: 2000, status: 'used' },
  { id: 'cp4', name: '치아관리 특별 혜택 쿠폰', description: '', discountAmount: 10000, status: 'used' },
  { id: 'cp5', name: '환한 미소 프로젝트 특별 할인 쿠폰', description: '', discountAmount: 5000, status: 'expired' },
  { id: 'cp6', name: '미소 업그레이드 지원 쿠폰', description: '', discountAmount: 3000, status: 'expired' },
  { id: 'cp7', name: '첫방문 할인쿠폰', description: '', discountAmount: 20000, status: 'available' },
  { id: 'cp8', name: '봄맞이 할인쿠폰', description: '', discountAmount: 3000, status: 'available' },
];

export const pointHistory: PointHistory[] = [
  { id: 'pt1', type: 'use', description: '포인트사용', amount: -500, date: '2026년3월14일' },
  { id: 'pt2', type: 'earn', description: '결제적립', amount: 500, date: '2026년3월14일' },
  { id: 'pt3', type: 'earn', description: '후기작성', amount: 500, date: '2026년3월14일' },
  { id: 'pt4', type: 'earn', description: '결제적립', amount: 500, date: '2026년3월14일' },
  { id: 'pt5', type: 'earn', description: '이벤트적립', amount: 2000, date: '2026년3월14일' },
  { id: 'pt6', type: 'earn', description: '첫가입 적립', amount: 2000, date: '2026년3월14일' },
];

export const announcements = [
  {
    id: 'a1',
    title: '서비스 약관 개정 안내',
    date: '2026.02.24',
    content:
      '안녕하세요, 키닥터입니다.\n\n더 나은 서비스 제공을 위해 서비스 이용약관이 일부 개정됩니다.\n\n변경 주요 내용\n- 개인정보 수집·이용 범위 명확화\n- 환불 정책 세부 조항 추가\n- 부정 이용에 대한 제재 절차 개정\n\n시행일: 2026년 3월 10일\n개정된 약관은 시행일부터 자동 적용되며, 동의하지 않는 경우 서비스 이용이 제한될 수 있습니다.',
  },
  {
    id: 'a2',
    title: '1.2.06 업데이트 안내',
    date: '2026.02.22',
    content:
      '1.2.06 버전 업데이트 내역을 안내드립니다.\n\n신규 기능\n- 실시간 의사에게 질문 섹션 추가\n- 병원 상세 네이버 지도 연동\n- 커뮤니티 자동 스크롤 지원\n\n개선 사항\n- 상품 카드 렌더링 속도 개선\n- 모달 백그라운드 스크롤 이슈 수정\n- 고정바 레이아웃 최적화\n\n앱 스토어에서 최신 버전으로 업데이트해주세요.',
  },
  {
    id: 'a3',
    title: '정부 지침으로 진료에 대한 내용이 변경됩니다.',
    date: '2026.01.02',
    content:
      '보건복지부 고시 개정에 따라 일부 진료 항목 표기가 변경됩니다.\n\n주요 변경사항\n- 비급여 진료비 표기 의무화\n- 수술 전후 사진 게시 가이드라인 적용\n- 광고성 문구 사용 제한\n\n해당 내용은 2026년 1월 15일부터 플랫폼 전체에 적용되며, 입점 병원은 상품 정보를 검토 후 수정해주시기 바랍니다.',
  },
  {
    id: 'a4',
    title: '2026년 3월 보안 업데이트 공지',
    date: '2026.03.01',
    content:
      '보안 강화를 위한 정기 업데이트가 진행됩니다.\n\n작업 일시: 2026년 3월 15일 02:00 ~ 04:00 (2시간)\n영향 범위: 로그인 일시 지연 가능\n\n작업 중 로그인이 필요한 기능은 일시적으로 제한될 수 있으니 양해 부탁드립니다.',
  },
  {
    id: 'a5',
    title: '2026년 4월 신규 기능 출시 예정',
    date: '2026.04.15',
    content:
      '4월에 출시 예정인 신규 기능을 소개합니다.\n\n- AI 기반 진료 추천\n- 1:1 실시간 상담 채팅\n- 간편 결제 확대 (네이버페이, 토스)\n- 리뷰 영상 업로드\n\n자세한 내용은 출시일에 맞춰 공지드리겠습니다.',
  },
  {
    id: 'a6',
    title: '회원 혜택 정책 변경 안내',
    date: '2026.05.10',
    content:
      '회원 등급 및 혜택 정책이 일부 개정됩니다.\n\n- 포인트 적립률 상향 (1% → 1.5%)\n- VIP 등급 신규 신설\n- 쿠폰 유효기간 확대 (30일 → 60일)\n\n시행일: 2026년 6월 1일',
  },
  {
    id: 'a7',
    title: '시스템 점검 일정 안내',
    date: '2026.06.05',
    content:
      '안정적인 서비스 제공을 위한 시스템 점검이 진행됩니다.\n\n일시: 2026년 6월 12일 00:00 ~ 06:00\n영향: 전체 서비스 일시 중단\n\n점검 중에는 앱/웹 접속이 불가합니다. 이용에 참고 부탁드립니다.',
  },
  {
    id: 'a8',
    title: '고객 의견 수렴을 위한 설문조사 실시',
    date: '2026.07.01',
    content:
      '더 나은 서비스를 위한 고객 설문조사가 진행됩니다.\n\n참여 기간: 2026년 7월 1일 ~ 7월 14일\n참여 혜택: 추첨을 통해 커피 쿠폰 증정 (100명)\n\n마이페이지 배너를 통해 참여할 수 있습니다.',
  },
];
